config/routes.rb
Itronaut::Application.routes.draw do
  
  get '/show_down' => 'contents#show', :page => 4;
  
  get '/about_us' => 'contents#show', :page => 3;
  
  get '/contact' => 'contents#show', :page => 2;
  
  root :to => 'contents#show', :page => 1;
 
  get '/home' => 'contents#show', :page => 1;
  
  resources :contents

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  
=begin

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end
  
  
  # GET /contents/1
  # GET /contents/1.json
  def show
    if params[:id]
      @content = Content.find(params[:id])
    elsif params[:name]
      @content = Content.find_by_name(params[:name])
    end
    
    @home = Content.find_by_name('home')
    @contact = Content.find_by_name('contact')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end
  
=end
  
  def show
    @content = Content.find_by_page(params[:page])
    
    @home = Content.find_by_name('home')
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

=begin

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :ok }
    end
  end
  
=end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/about_us/index.html.haml
%h1 How do we work?

.block.first
	%canvas#first_circle.canvas{:width => '90', :height => '90'}
		%p
			Your browser doesn't support canvas.
	
	%p
		Legunt adipiscing imperdiet in sollemnes decima. Ea ut illum ad et lius. Me sed sed eu gothica autem. Litterarum blandit et littera ad legunt. Duis consequat commodo ex lectorum accumsan. Nobis vulputate illum quarta clari gothica.
					
.arrow_container
	.square
	.point

.block
	%canvas#second_circle.canvas{:width => '90', :height => '90'}
		%p
			Your browser doesn't support canvas.
	
	%p
		Non usus legere decima parum typi. Ut legunt in quis molestie nisl. Aliquip consuetudium dignissim diam est consequat. Investigationes placerat autem aliquip est videntur. Mirum autem velit quam claritatem et. Dolor quam consequat tation accumsan nisl. Claritatem iriure nisl parum nulla et.
		
.arrow_container
	.square
	.point

.block.last
	%canvas#third_circle.canvas{:width => '90', :height => '90'}
		%p
			Your browser doesn't support canvas.
	
	%p
		Facilisis nibh claritatem veniam consuetudium qui. Qui clari litterarum iis ii exerci. Tincidunt lorem veniam insitam magna ea. Liber claritas volutpat liber legentis facer. Option mazim tation nobis eodem eros.

	%p
		Claram videntur duis possim et typi. Vulputate ut qui claritatem option ut. Nostrud videntur lius quod sollemnes molestie. Id nibh nunc consuetudium ii legere.

app/views/application/_header.html.haml
%a{:href => content_path(@home)}
	.logo
		%img{:src => '/assets/overall/itronaut.png'}

.menu#home.first
	.text
		home

.line

.menu#about_us
	.text
		about us

.line

.menu#show_down
	.text
		show down

.line

.menu#contact.last
	.text
		contact

app/views/contact/index.html.haml
%h1 How to contact us?

.block.first.last
	#form
		%h2 Quick questions
		%form{:autocomplete => 'on'}
			%input#name.form_input{:type => 'text', :placeholder => 'Your name', :autofocus => 'autofocus'}
			%input#mail.form_input{:type => 'text', :placeholder => 'Your mail address'}
			%input#phone.form_input{:type => 'text', :placeholder => 'Your phone number'}
			%textarea#message.form_input{ :placeholder => 'Your message'}
			.button
				.button_text
					Submit
	
	#right_area
		%span#right
			%h2 Stay in touch
		#google_maps
			%iframe{:src => 'http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Brahmslaan+89,+Delft,+The+Netherlands&aq=0&oq=Br&sll=51.995703,4.33685&sspn=0.006976,0.01929&vpsrc=6&t=m&ie=UTF8&hq=&hnear=Brahmslaan+89,+Delft,+Zuid-Holland,+The+Netherlands&ll=52.118312,4.179611&spn=0.147568,0.344009&z=11&iwloc=A&output=embed'}
		
		#credentials
			#left
				%h3
					%span#itronaut itronaut
				Brahmslaan 89
				%br
				2625 BT, Delft
				%br
				the Netherlands
			
			#right
				%span#contact Telephone:
				+31 6 1022 3491
				%br
				%span#contact E-mail:
				%a{:href => 'mailto:info@itronaut.com'}info@itronaut.com

app/views/contents/_form.html.haml
= form_for @content do |f|
  -if @content.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content.errors.count, "error")} prohibited this content from being saved:"
      %ul
        - @content.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/contents/edit.html.haml
%h1 Editing content

= render 'form'

= link_to 'Show', @content
\|
= link_to 'Back', contents_path

app/views/contents/index.html.haml
%h1 Listing contents

%table
	%tr
		%th Name
		%th Location
		%th
		%th
		%th

	- @contents.each do |content|
		%tr
			%td= content.name
			%td= content.location
			%td= link_to 'Show', content
			%td= link_to 'Edit', edit_content_path(content)
			%td= link_to 'Destroy', content, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Content', new_content_path

app/views/contents/new.html.haml
%h1 New content

= render 'form'

= link_to 'Back', contents_path

app/views/contents/show.html.haml
=render :template => @content.location

app/views/home/index.html.haml
.stars
	.background
	.midground
	.foreground
	
	-# Move code
	-#.prologue#block1
		%span#balloon1
			%h1
				What is
				%span#itronaut itronaut
				?
		
		%span#balloon2
			%h1
				Balloon 2
		
		%span#balloon3
			%h1
				Balloon 3
	
	
	-# Appear code
	.prologue#balloon1
		%h1
			What is
			%span#itronaut itronaut
	
	.prologue#balloon2
		%h1
			Balloon 2
	
	.prologue#balloon3
		%h1
			Balloon 3
	
	
	.arrow
	
.choice_block
	.block1.offer.first
		.text
			%h2 Offer1
	
	.block2.offer
		.text
			%h2 Offer2
	
	.block3.offer.last
		.text
			%h2 Offer3

.promo_area
	.story
		%p
			Eodem est decima amet quam ut. Decima usus et fiant vero et. Quarta in facilisi typi doming ut. Nobis nibh qui diam est eu. Qui insitam eum parum non est. Sit nunc laoreet laoreet ex vero. Legunt facilisi ex dolore praesent processus. 

		%p
			Consequat te littera lorem eodem eleifend. Ad enim sollemnes lectorum tincidunt laoreet. Congue soluta nulla humanitatis nobis ipsum. Dynamicus in non decima qui qui. Dignissim eum minim qui dolore vero. Futurum feugiat processus eros option gothica. Saepius sequitur dynamicus tincidunt aliquip anteposuerit. 

		%p
			Blandit etiam autem legunt magna nulla. Et facit insitam suscipit qui est. Typi quis cum in vel in.
	
		.button
			.button_text
				Read more

app/views/layouts/application.html.haml
!!!5
%html
	%head
		= stylesheet_link_tag    'application'
		= javascript_include_tag 'application'
		= csrf_meta_tags
		%title
			itronaut - 
			=if @content then @content.name.capitalize! else controller.controller_name.gsub('_', ' ').split(' ').each{|word| word.capitalize!}.join(' ') end
		


	%body{ :class => if @content then @content.name.downcase! else controller.controller_name end }
		#header_background
			#bottom_ridge
		#stage
			.header
				= render 'header' rescue nil
			.content
				= yield
			.footer
				= render 'footer' rescue nil

app/views/show_down/index.html.haml
.block.first.last
	%canvas#star.canvas{:width => '500', :height => '150'}
		%p
			Your browser doesn't support canvas.

.block.first.last
	%p
		.button
			.button_text
				Click here to change canvas

.block.first.last
	